### ISSUE TITLE
Colors appear off (color palette?) with Colecovision and SG-1000 versions

### ISSUE THREAD

**Issue by RetroInVitro** [nanochess/240pTestSuite_colecovision#1]
![colecovision-240p_test_suite-1](https://github.com/nanochess/240pTestSuite_colecovision/assets/32917592/72db4cdb-98ce-4f65-a545-36a659d70e7f)
![segamastersystem-240p_test_suite-colors](https://github.com/nanochess/240pTestSuite_colecovision/assets/32917592/2c064fc2-7a3f-4046-b18f-0236f6994ab6)

The CV version is ran on a real console.  Using both an AtariMax and Chameleon cart.  Also have a Backbit Pro if that needs to be tested on.

The SG-1000 version is ran on a Sega Master System.

All consoles are N.American.

**Comment by nanochess** [comment]
The appearance is correct. The palette for TMS9928 cannot be changed so the colors for Gillian are approximate. Only in MSX2, Gillian appear as originally devised.

**Comment by RetroInVitro** [comment]
> Only in MSX2, Gillian appear as originally devised.

Thank you for the quick response.   I see the screenshot at the main GitHub page and see the correct colors.  Is this because you used the MSX2 port for the picture attached:

![Screen Shot 2024-03-20 at 2 55 26 PM](https://github.com/nanochess/240pTestSuite_colecovision/assets/32917592/600b04d9-af7e-4566-8ff8-b18e39c7bde2)

**Comment by nanochess** [comment]
Sorry for that. I really should put also a picture with my Colecovision

**Comment by nanochess** [comment]
Added MSX1 screenshot.
